### ISSUE TITLE
How did you assign multiple countries to a paper?

### ISSUE THREAD

**Issue by nd7141** [marekrei/ml_nlp_paper_data#1]
It's a great analysis. One question. 

If a in paper we have three authors: Author 1 (country A), Author 2 (country A and country B), and Author 3 (country C). How will you redistribute a paper among three countries? 
Does each country A,B,C will get count +1? Or A will get 2? Or something else?

**Comment by marekrei** [comment]
Each country and organization is only counted once per paper.

**Comment by nd7141** [comment]
Thank you @marekrei
